config/routes.rb
Rails.application.routes.draw do
  get 'contact/index'

  get 'about/index'

  get 'welcome/index'

  resources :articles

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
  end

  def create 
    @article = Article.new(params.require(:article).permit(:title, :text))
    @article.save
    redirect_to @article
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<div class="about-page">
<h1>About page bitches!</h1>
</div>

app/views/articles/index.html.erb
<h1>Previous Blog Posts</h1>
<%= link_to 'New article', new_article_path %>
<table>
 <tr>
   <th>Title</th>
   <th>Text</th>
 </tr>

 <% @articles.each do |article| %>
   <tr>
     <td><%= article.title %></td>
     <td><%= article.text %></td>
     <td><%= link_to 'Show', article_path(article) %></td>
   </tr>
 <% end %>
</table>

app/views/articles/new.html.erb
<div class="articles-page">
  <h1>New Blog Post here . . .</h1>
  <%= form_with scope: :article, url: articles_path, local: true do |form| %>
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>
  
    <p>
      <%= form.label :text %><br>
      <%= form.text_area :text %>
    </p>
  
    <p>
      <%= form.submit %>
    </p>
  <% end %>
  <%= link_to 'Back', articles_path %>
</div>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

app/views/contact/index.html.erb
<div class="contact-page">
  <h1>Contact Page</h1>
  <ul>
    <li>matt.a.larson@gmail.com</li>
    <li>612.251.6818</li>
    <li><a href="https://www.linkedin.com/in/mattalarson/">LinkedIn</a></li>
    <li><a href="https://twitter.com/mattlarsonmusic">Twitter</a></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header class="header">
    <h1>Welcome to my Rails blog!</h1>
  </header>
  <nav>
    <a href="/welcome/index">Home</a>
    <a href="/about/index">About Page</a>
    <a href="/articles/new">Create Article</a>
    <a href="/articles">My Blog</a>
    <a href="/contact/index">Contact Page</a>
  </nav>
  <hr>
  <body>
    <%= yield %>
  </body>
  <footer>©2017, built by <a href="http://www.matthewlarsondev.com/">Matt Larson</a></footer>
</html>

app/views/welcome/index.html.erb
<main>
  <p>This site was built with Ruby on Rails. I first started learning RoR on November 14th, 2017.
  So far, it is incredibly intuitive. I have started by following the walkthrough on <a href="http://guides.rubyonrails.org/getting_started.html">rubyonrails.org</a>.
  We have a pretty basic blog setup with the ability to Create and view posts. I have also utilized Sass for styling. There are plenty of links 
  for site navigation, as well as Navbar that takes you anywhere you need to go.</p>
  <%= link_to 'My Blog', controller: 'articles' %>
</main>